name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  mingw:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
    strategy:
      matrix:
        target: [x86_64-w64-mingw32]
    steps:
      - uses: actions/checkout@v3

