name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  mingw:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
    strategy:
      matrix:
        target: [x86_64-w64-mingw32]
    steps:
      - uses: actions/checkout@v3

      - name: Install buildx
        uses: docker/setup-buildx-action@v2

      - name: Build target base image
        uses: docker/build-push-action@v4
        with:
          context: images/base
          pull: true
          push: true
          tags: base-image:latest
